package org.lzy.kaggle.eloRecommendation

import java.sql.Timestamp

import com.salesforce.op.features.FeatureBuilder
import com.salesforce.op.features.types.DateTime

case class Record(

                   card_id: String,
                   first_active_month: String,
                   feature_1: Int,
                   feature_2: Int,
                   feature_3: Int,
                   target: Double,
                   new_installments_sum_stddev: Option[Double],
                   new_installments_sum_avg: Option[Double],
                   new_installments_min_stddev: Option[Double],
                   new_installments_min_avg: Option[Double],
                   new_installments_max_stddev: Option[Double],
                   new_installments_max_avg: Option[Double],
                   new_installments_std_stddev: Option[Double],
                   new_installments_std_avg: Option[Double],
                   new_purchase_amount_sum_stddev: Option[Double],
                   new_purchase_amount_sum_avg: Option[Double],
                   new_purchase_amount_min_stddev: Option[Double],
                   new_purchase_amount_min_avg: Option[Double],
                   new_purchase_amount_max_stddev: Option[Double],
                   new_purchase_amount_max_avg: Option[Double],
                   new_purchase_amount_std_stddev: Option[Double],
                   new_purchase_amount_std_avg: Option[Double],
                   new_category_1_avg: Option[Double],
                   new_category_1_std: Option[Double],
                   new_category_2_avg: Option[Double],
                   new_category_2_std: Option[Double],
                   new_city_id_count: Option[Long],
                   new_state_id_count: Option[Long],
                   new_subsector_id_count: Option[Long],
                   new_month_lag_avg: Option[Double],
                   new_diff_month_avg: Option[Double],
                   new_week_avg: Option[Double],
                   new_count_month: Option[Double],
                   new_purchase_date_max: Option[Long],
                   new_purchase_date_min: Option[Long],
                                      new_purchase_date_list:Option[Seq[Long]],
                   new_category_1_list: Option[Seq[Double]],
                   new_category_2_list: Option[Seq[Double]],

                   auth_installments_sum_stddev: Option[Double],
                   auth_installments_sum_avg: Option[Double],
                   auth_installments_min_stddev: Option[Double],
                   auth_installments_min_avg: Option[Double],
                   auth_installments_max_stddev: Option[Double],
                   auth_installments_max_avg: Option[Double],
                   auth_installments_std_stddev: Option[Double],
                   auth_installments_std_avg: Option[Double],
                   auth_purchase_amount_sum_stddev: Option[Double],
                   auth_purchase_amount_sum_avg: Option[Double],
                   auth_purchase_amount_min_stddev: Option[Double],
                   auth_purchase_amount_min_avg: Option[Double],
                   auth_purchase_amount_max_stddev: Option[Double],
                   auth_purchase_amount_max_avg: Option[Double],
                   auth_purchase_amount_std_stddev: Option[Double],
                   auth_purchase_amount_std_avg: Option[Double],
                   auth_category_1_avg: Option[Double],
                   auth_category_1_std: Option[Double],
                   auth_category_2_avg: Option[Double],
                   auth_category_2_std: Option[Double],
                   auth_city_id_count: Option[Long],
                   auth_state_id_count: Option[Long],
                   auth_subsector_id_count: Option[Long],
                   auth_month_lag_avg: Option[Double],
                   auth_diff_month_avg: Option[Double],
                   auth_week_avg: Option[Double],
                   auth_count_month: Option[Double],
                   auth_purchase_date_max: Option[Long],
                   auth_purchase_date_min: Option[Long],
                                      auth_purchase_date_list:Option[List[Long]],
                   auth_category_1_list: Option[Seq[Double]],
                   auth_category_2_list: Option[Seq[Double]],


                   hist_installments_sum_stddev: Option[Double],
                   hist_installments_sum_avg: Option[Double],
                   hist_installments_min_stddev: Option[Double],
                   hist_installments_min_avg: Option[Double],
                   hist_installments_max_stddev: Option[Double],
                   hist_installments_max_avg: Option[Double],
                   hist_installments_std_stddev: Option[Double],
                   hist_installments_std_avg: Option[Double],
                   hist_purchase_amount_sum_stddev: Option[Double],
                   hist_purchase_amount_sum_avg: Option[Double],
                   hist_purchase_amount_min_stddev: Option[Double],
                   hist_purchase_amount_min_avg: Option[Double],
                   hist_purchase_amount_max_stddev: Option[Double],
                   hist_purchase_amount_max_avg: Option[Double],
                   hist_purchase_amount_std_stddev: Option[Double],
                   hist_purchase_amount_std_avg: Option[Double],
                   hist_category_1_avg: Option[Double],
                   hist_category_1_std: Option[Double],
                   hist_category_2_avg: Option[Double],
                   hist_category_2_std: Option[Double],
                   hist_city_id_count: Option[Long],
                   hist_state_id_count: Option[Long],
                   hist_subsector_id_count: Option[Long],
                   hist_month_lag_avg: Option[Double],
                   hist_diff_month_avg: Option[Double],
                   hist_week_avg: Option[Double],
                   hist_count_month: Option[Double],
                   hist_purchase_date_max: Option[Long],
                   hist_purchase_date_min: Option[Long],
                                      hist_purchase_date_list:Option[List[Long]],
                   hist_category_1_list: Option[Seq[Double]],
                   hist_category_2_list: Option[Seq[Double]]
                 )
